language: scala

scala:
  - 2.12.2
  - 2.11.11
jdk:
  - oraclejdk8

script:
  - sbt clean test

# Snapshot publishing via Travis courtesy of Jan Machacek, thanks!
# http://www.cakesolutions.net/teamblogs/publishing-artefacts-to-oss-sonatype-nexus-using-sbt-and-travis-ci
after_success:
   - "[[ $TRAVIS_BRANCH == \"master\" ]] && { sbt publish; };"

env:
  global:
    - secure: "TRDTLUiwGoI1O0dcP6F96Djb7xlRlaowrEWMrL+lUZizlCiSJ3/RdqDDGspzS8NQkBRXrqHhyTf2RIwfxu3J0nstlzfTwEpNhF698EhpHVVR9srBsgr8+iinS5WCUcotrMKDWIOpLPERbw9tap3HJQPJiXAUDqzPixjThb/BpXg="
    - secure: "U22HGF01uu6rruU+M2y6dokf2EHM5d9r/VxwSPRrxW6m34KlVhIfPtuobo+mAfwDRC25+nedPe/YWcPRm50kbX7pYzGVHAkP1A2SIJXVkvqmQb1qezu1D3qu3mSHoZbvLvWVUJX0ige7QHOfAW2lypIFFDJcbiwXqZN3q4IB+bs="

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
