language: scala

scala:
  - 2.12.2
  - 2.11.11

script:
  - sbt clean test

jdk:
  - oraclejdk8

env:
  global:
    - secure: TRDTLUiwGoI1O0dcP6F96Djb7xlRlaowrEWMrL+lUZizlCiSJ3/RdqDDGspzS8NQkBRXrqHhyTf2RIwfxu3J0nstlzfTwEpNhF698EhpHVVR9srBsgr8+iinS5WCUcotrMKDWIOpLPERbw9tap3HJQPJiXAUDqzPixjThb/BpXg=
    - secure: U22HGF01uu6rruU+M2y6dokf2EHM5d9r/VxwSPRrxW6m34KlVhIfPtuobo+mAfwDRC25+nedPe/YWcPRm50kbX7pYzGVHAkP1A2SIJXVkvqmQb1qezu1D3qu3mSHoZbvLvWVUJX0ige7QHOfAW2lypIFFDJcbiwXqZN3q4IB+bs=

after_success:
   - bash env
   - "[[ $TRAVIS_BRANCH == \"master\" ]] && { sbt publish; };"

#
#cache:
#  directories:
#    - $HOME/.ivy2/cache
#    - $HOME/.sbt/boot/
