language: scala

scala:
  - 2.12.2
  - 2.11.11

script:
  - sbt clean test

jdk:
  - oraclejdk8

env:
  global:
    - secure: "dKWd9eEWN3mjifVdhjBcGb276KTuRSICVJJlOtGotkcvj0YoNiaOol5ExSZ1U4aqTsopqPe9Fm67gkQo950MCPIeu+l1Hap9YB63wD1krQlJUA5dPG7m1MQ/B3XJDo5sDQ8soI+NWdGv6XeSrgFjZgD9Yo1rzoqYWrnweOfP9S3veRVX1D4rymHdfhGMRjyEdVQ3nrNuwI6tOcKmA4VsmcySjCKLoYdP4OGNU5Bg111lUNayoMJMqxy7SKVbt8WCb0fC9WW8+K2na39WceC6WRxIuO3sLKuj+sIo4NBN3rdbnp+MNL/hXnnLPVF7qdwemwPpC8bcHqHdm3IVwIgctgj6k/d0XZlaSsPUnYHxQYEcxyjlslA0ZZy6A4M3UuP0Kc1/WjjjxC7q2p75hm76K0wRkFcxlklSMyAuVoP+qNQdwUZ/UKVXPG17BP31TjRcaJRqF9nPDi/RpKCJlP2lH7FIS5WAJfANo0WaoWEfp/vty4xQh5NjakjLCfkKyAmwn6lmcNtlZFT0jKWMsTCygidoxIZ1ZyEcseLk9T0WD7WFnlnb7u0ypjwFvC8aFZVpYUC4FjSUVT/YKeGLLclmaBL0wGbkRWtPwRVqqrrLQO53brFRBKGuqWr8rKwEqgaTv6Sbsuk9iBFmWjRDxSgA2ljby2VQ4YvfWBu9z+456gM="
    - secure: "Ggbqb+sQE61y1o10fgG1oHDisqk1Zh4/xAIbOhwVMZLC8SJ7pwSVny7pZuWbqgM1gbsOrS78GVhjsB4XKp3oEz5+x8DboIXGzpPI+MUrLMNjNDnzYJWrZwGikqxeBk7Fu+jIGlWjBK6/FhYb9S9Cpho91siqmRFUeX7+PwhbpRNqyby32cefgL/6L2swDfAGhNdu9H1r1/FAx469vM6hpDtw+TuiYmkv8RQT4Mrqh6zufnhb5Obmx6XT2+b0OrreEpxP5CaBDhUg3RH5I2nuGyN0aMkMlvsIHXIZBTMVJ1MJRufhNXm+e+wcTTwa5UJz2716nD7j2vO4vg7h+sQAuoBrvxHesAL6mvl7Ryl7Rx1Smd7YO7JRdvh7+lvTSSvhUT5CVIppBtCegPrBfmBUwMQct97ADpVU11k7PoRZrS5WKc4Cx4KHSYlZPxIuTuvtkY8L0kCrAM7iswEX7oa5L3HYpJzES+H6IdcLEx8Njd6h6G2pdqwEbjpq3iOje5HFIbd/Ai7i61zqjuZRFjpZKni7XAteS+FaIplMTNqJDvHWhsD+qJmRFApLX9xKMzOi3dWezfeNHPBJ6EgpXbK/PyIcGYPwO4lDbQEoCjts4TGB8B0dQK3GYziOkziV9VBIdyXexDwsTAUHnxYbT+QvJpPSBobMzQmR9+pinIzmQDQ="

after_success:
   - bash env
   - "[[ $TRAVIS_BRANCH == \"master\" ]] && { sbt publish; };"

#
#cache:
#  directories:
#    - $HOME/.ivy2/cache
#    - $HOME/.sbt/boot/
